Settings:
  apply-effect-radius: 4
  regen-health-after: 60 # Em segundos.

Messages:
  insufficient-permission: "&cVocê não tem permissão."
  invalid-player: "&cEsse jogador não existe ou não está online."
  has-active-boss: "&cVocê já possui um boss ativo, mate-o para gerar outro!"
  boss-spawned: "&aBoss gerado! &cMate-o&a."
  boss-cmd:
    available-bosses: "&aBosses: (%available_bosses%)"
    invalid-boss: "&cEsse boss não existe."
    send-boss-sender: "&aVocê enviou um boss com sucesso para %player_name%."
    send-boss-target: "&aVocê recebeu um boss de %sender_name%."
    help:
      - '&aGiveBoss Commands:'
      - '&e/giveboss <boss> <jogador> &b- Enviar boss especifico para um jogador.'
      - '&e/giveboss lista &b- Lista de bosses disponível.'
  custom-sword-slayer-cmd:
    available-swords: "&aEspadas: (%available_swords%)"
    invalid-sword: "&cEssa espada não existe."
    send-sword-sender: "&aVocê enviou uma espada com sucesso para %player_name%."
    send-sword-target: "&aVocê recebeu uma espada de %sender_name%."
    help:
      - '&aGiveMatadora Commands:'
      - '&e/givematadora <espada> <jogador> &b- Enviar espada matadora de boss para um jogador.'
      - '&e/givematadora lista &b- Lista de espadas disponível.'

Bosses:
  beast:
    display-name: "&bBeast &c%current_health%&7/&c%max_health%"
    health: 150000
    small: true
    # Esse boss leva dano apenas com
    # a matadora?
    # true - Apenas matadora.
    # false - Qualquer espada.
    use-custom-sword: false
    # A cada segundo vamos verificar
    # se a chance é compatível para
    # iniciar algum efeito.
    chance-to-play-effects: 10
    # Porcentagem que a vida do boss
    # vai regenerar por segundo.
    # (Isso só é chamado se o jogador
    # ficar um tempo sem ataca-lo).
    health-regen-per-sec: 1 # 1% da vida total.
    # Os efeitos listados abaixo,
    # são os efeitos disponíveis para
    # esse boss.
    effects:
      # Efeitos que o boss pode aplicar no jogador.
      # Efeitos disponíveis: { DAMAGE, POISON, BLINDNESS, SLAP }!
      DAMAGE:
        chance: 10 # 10% de chance desse efeito acontecer.
        damage: 0.5 # Sempre que for aplicado esse efeito, será descontado esse valor da vida do jogador.
        play-thunder: true # Raio.
      POISON:
        chance: 5
        damage: 0.01
        # Duração do efeito.
        duration: 3 # Em segundos
        amplifier: 2
      BLINDNESS:
        chance: 35
        damage: 0.01
        duration: 3 # Em segundos
        amplifier: 2
      SLAP:
        chance: 15
        amplifier: 3
        play-thunder: true
    boss-armor:
      0:
        type: "STICK"
        name: "&7"
        lore: {}
        armor-position: "HAND" # ArmorStand vai segurar este item na mão.
      1:
        type: "SKULL_ITEM:3"
        owner: "hypixel"
        name: "&7"
        lore: {}
        armor-position: "HELMET" # Esse item fica na cabeça do ArmorStand.
      2:
        type: "LEATHER_CHESTPLATE"
        name: "&7"
        lore: {}
        color:
          r: 255
          g: 0
          b: 0
        armor-position: "CHESTPLATE" # Peitoral do ArmorStand.
      3:
        type: "LEATHER_LEGGINGS"
        name: "&7"
        lore: {}
        color:
          r: 255
          g: 0
          b: 0
        armor-position: "LEGGINGS" # Calça do ArmorStand.
      4:
        type: "LEATHER_BOOTS"
        name: "&7"
        lore: {}
        color:
          r: 255
          g: 0
          b: 0
        armor-position: "BOOTS" # Botas do ArmorStand.
    spawn-egg:
      type: "SKULL_ITEM"
      owner: "hypixel"
      name: "&7Boss - hypixel"
      lore:
        - ''
        - '&7Clique no chão para nascer'
        - '&7esse boss!'
        - ''
        - '&7Dificuldade: &fFácil'
    rewards:
      1:
        chance: 100
        commands:
          - '[PLAYER]/c'
          - '[CONSOLE]/whisper %player_name% Boss foi morto.'
        messages:
          - '&7----------'
          - '&fVocê matou o &bBeast&f!'
          - '&7----------'
        items:
          1:
            type: "DIAMOND"
            name: "&bDiamante"
            lore:
              - ''
              - '&cYey! Você matou o &bBeast &c%player_name%'

# Espada matadora de boss.
Boss-Sword-Slayer:
  1:
    type: "STICK"
    name: "&cMatadora de Boss"
    lore:
      - ''
      - '&7Com essa espada você'
      - '&7mata o boss instantâneo.'
    enchants:
      - 'DAMAGE_ALL,5'
    # Dano que essa espada causa no boss.
    damage-cause: 150000