name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SkyVox_
website: "http://www.skydhs.com"

# Dependencies.
# Plugin won't enable without those plugins listed below.
#depend: {}

# Soft dependencies.
#softdepend: {}

# Main class.
main: com.skydhs.boss.Core

# Plugin commands.
commands:
  giveboss:
    description: "Send boss for an specific player or check all available bosses."
    usage: "/giveboss"
  givematadora:
    description: "Send the boss slayer sword for a specific player."
    usage: "/givematadora"